[meta]
name     = "Editor Camera Hotkeys"
author   = "XertroV"
category = "Map Editor"
version  = "0.2.4"
siteid = 323

[script]
#__DEFINES__
# dependencies = ["Camera"]
# optional_dependencies = ["Editor"]
